baseURL = "https://deleteonerror.com/"
languageCode = "en-us"
title = "Experiment -> Fail -> Learn -> Repeat"


baseurl = "/"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "delete on error"
    subtitle = "Experiment -> Fail -> Learn -> Repeat"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "delete on error"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      # [[languages.en.menu.main]]
      #   identifier = "showcase"
      #   name = "Showcase"
      #   url = "/showcase"

[taxonomies]
   tag = "tags"
   category = "categories"


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
